"""initial production schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-04
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("users", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("email", sa.String(320), nullable=False), sa.Column("password_hash", sa.String(512)), sa.Column("display_name", sa.String(120), nullable=False), sa.Column("auth_provider", sa.String(32), nullable=False, server_default="email"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_table("career_profiles", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("current_role", sa.String(160), nullable=False), sa.Column("target_role", sa.String(160), nullable=False), sa.Column("learning_style", sa.String(80), nullable=False), sa.Column("target_company", sa.String(160)), sa.Column("target_salary", sa.Numeric()), sa.Column("preferred_daily_minutes", sa.Integer(), nullable=False), sa.Column("mentor_tone", sa.String(40), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("roadmaps", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(220), nullable=False), sa.Column("duration_days", sa.Integer(), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("generated_by", sa.String(32), nullable=False), sa.Column("started_at", sa.Date()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("roadmap_weeks", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("roadmap_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("roadmaps.id", ondelete="CASCADE"), nullable=False), sa.Column("week_number", sa.Integer(), nullable=False), sa.Column("theme", sa.String(220), nullable=False), sa.Column("objectives", postgresql.ARRAY(sa.Text()), nullable=False, server_default="{}"), sa.Column("is_locked", sa.Boolean(), nullable=False, server_default=sa.text("true")), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("missions", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("roadmap_week_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("roadmap_weeks.id", ondelete="CASCADE"), nullable=False), sa.Column("day_number", sa.Integer(), nullable=False), sa.Column("title", sa.String(220), nullable=False), sa.Column("objective", sa.Text(), nullable=False), sa.Column("business_context", sa.Text(), nullable=False), sa.Column("learning_topic", sa.String(220), nullable=False), sa.Column("practical_task", sa.Text(), nullable=False), sa.Column("documentation_prompt", sa.Text(), nullable=False), sa.Column("reflection_prompt", sa.Text(), nullable=False), sa.Column("interview_question", sa.Text(), nullable=False), sa.Column("difficulty", sa.Integer(), nullable=False), sa.Column("estimated_minutes", sa.Integer(), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("unlocked_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("mission_tasks", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("mission_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("missions.id", ondelete="CASCADE"), nullable=False), sa.Column("type", sa.String(40), nullable=False), sa.Column("title", sa.String(220), nullable=False), sa.Column("instructions", sa.Text(), nullable=False), sa.Column("skill_improved", sa.String(140), nullable=False), sa.Column("completion_criteria", sa.Text(), nullable=False), sa.Column("status", sa.String(32), nullable=False))
    op.create_table("mission_evidence", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("mission_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("missions.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("evidence_type", sa.String(40), nullable=False), sa.Column("reference_id", postgresql.UUID(as_uuid=True)), sa.Column("url", sa.Text()), sa.Column("summary", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("notes", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("mission_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("missions.id", ondelete="SET NULL")), sa.Column("title", sa.String(220), nullable=False), sa.Column("body_markdown", sa.Text(), nullable=False), sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=False, server_default="{}"), sa.Column("folder", sa.String(120)), sa.Column("embedding_status", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("journal_entries", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("mission_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("missions.id", ondelete="SET NULL")), sa.Column("entry_date", sa.Date(), nullable=False), sa.Column("wins", sa.Text()), sa.Column("failures", sa.Text()), sa.Column("lessons_learned", sa.Text()), sa.Column("root_cause", sa.Text()), sa.Column("automation_ideas", sa.Text()), sa.Column("reflection", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("reviews", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("review_type", sa.String(32), nullable=False), sa.Column("period_start", sa.Date(), nullable=False), sa.Column("period_end", sa.Date(), nullable=False), sa.Column("metrics_json", postgresql.JSONB(), nullable=False), sa.Column("ai_feedback", sa.Text(), nullable=False), sa.Column("improvement_plan", sa.Text(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("dashboard_snapshots", sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True), sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True), sa.Column("payload", postgresql.JSONB(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))


def downgrade() -> None:
    for table in ["dashboard_snapshots", "reviews", "journal_entries", "notes", "mission_evidence", "mission_tasks", "missions", "roadmap_weeks", "roadmaps", "career_profiles", "users"]:
        op.drop_table(table)
